--ANSWERBOARD

DROP TABLE ANSWERBOARD
DROP SEQUENCE ANSWERNOSEQ
DROP SEQUENCE GROUPNOSEQ

CREATE SEQUENCE ANSWERNOSEQ
CREATE SEQUENCE GROUPNOSEQ

CREATE TABLE ANSWERBOARD(
	ANSWER_NO NUMBER NOT NULL,
	USERBOARD_NO NUMBER NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	ANSWER_GROUPNO NUMBER NOT NULL,
	ANSWER_GROUPSEQ NUMBER NOT NULL,
	ANSWER_TITLETAB NUMBER NOT NULL,
	ANSWER_CONTANT VARCHAR2(2000) NOT NULL,
	ANSWER_REGDATE DATE NOT NULL,
	ANSWER_DELFLAG VARCHAR2(2) NOT NULL,
	
	CONSTRAINT ANSWER_PK_NO PRIMARY KEY(ANSWER_NO),
	CONSTRAINT ANSWER_FK_USERBOARD_NO FOREIGN KEY(USERBOARD_NO)
		REFERENCES USERBOARD(USERBOARD_NO) ON DELETE CASCADE,
	CONSTRAINT ANSWER_FK_MEMBER_NO FOREIGN KEY(MEMBER_NO)
		REFERENCES MEMBER(MEMBER_NO),
	CONSTRAINT ANSWER_CK_DELFLAG CHECK(ANSWER_DELFLAG IN('Y','N'))
)

INSERT INTO ANSWERBOARD
VALUES(
	ANSWERNOSEQ.NEXTVAL, 3, 1, ANSWERNOSEQ.NEXTVAL, 1, 0, 'TEST', SYSDATE, 'N'
)

SELECT * FROM ANSWERBOARD