--CALENDAR

DROP TABLE CALENDAR
DROP SEQUENCE CALENDARSEQ

CREATE SEQUENCE CALENDARSEQ

CREATE TABLE CALENDAR(
	CAL_NO NUMBER NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	CAL_TITLE VARCHAR2(500) NOT NULL,
	CAL_CONTENT VARCHAR2(4000) NOT NULL,
	CAL_MDATE VARCHAR2(12) NOT NULL,
	CAL_REGDATE DATE NOT NULL,
	
	CONSTRAINT CAL_NO_PK PRIMARY KEY(CAL_NO),
	CONSTRAINT CAL_FK_MEMBER_NO FOREIGN KEY(MEMBER_NO) 
		REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE
)

INSERT INTO CALENDAR
VALUES(
	CALENDARSEQ.NEXTVAL,
	1, 'calendar title', 'calendar content', '200101', SYSDATE
)

SELECT * FROM CALENDAR