--CHAT_ROOM

DROP TABLE CHAT_ROOM;
DROP SEQUENCE CHAT_ROOM_SEQ;

CREATE SEQUENCE CHAT_ROOM_SEQ;

CREATE TABLE CHAT_ROOM(
	CHAT_ROOM_NO NUMBER NOT NULL,
	CHAT_ROOM_NAME VARCHAR2(100) NOT NULL,
	
	CONSTRAINT CHAT_ROOM_PK PRIMARY KEY(CHAT_ROOM_NO)
)

INSERT INTO CHAT_ROOM
VALUES(CHAT_ROOM_SEQ.NEXTVAL, 'CHAT-ROOM-NAME');

SELECT * FROM CHAT_ROOM

--CHAT_USER

DROP TABLE CHAT_USER;


CREATE TABLE CHAT_USER(
	CHAT_ROOM_NO NUMBER NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	FIRST_CHAT_NO NUMBER NOT NULL,
	LAST_CHAT_NO NUMBER NOT NULL,
	
	CONSTRAINT CHAT_USER_FK_ROOMNO FOREIGN KEY(CHAT_ROOM_NO)
		REFERENCES CHAT_ROOM(CHAT_ROOM_NO) ON DELETE CASCADE,
	CONSTRAINT CHAT_USER_FK_MEMBER FOREIGN KEY(MEMBER_NO)
		REFERENCES MEMBER(MEMBER_NO)
)

INSERT INTO CHAT_USER VALUES(44, 784, 27, 27);

SELECT * FROM CHAT_USER

UPDATE CHAT_USER 
		SET LAST_CHAT_NO = (SELECT MAX(CHAT_NO) FROM CHAT WHERE CHAT_ROOM_NO = 44)
		WHERE CHAT_ROOM_NO = 44
		AND MEMBER_NO = 784


--CHAT

DROP TABLE CHAT
DROP SEQUENCE CHAT_SEQ;

CREATE SEQUENCE CHAT_SEQ;

CREATE TABLE CHAT(
	CHAT_NO NUMBER NOT NULL,
	CHAT_ROOM_NO NUMBER NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	MEMBER_ID VARCHAR2(20) NOT NULL,
	CHAT_CONTENT VARCHAR2(3000) NOT NULL,
	CHAT_REGDATE DATE NOT NULL,
	
	CONSTRAINT CHAT_PK PRIMARY KEY(CHAT_NO),
	CONSTRAINT CHAT_ROOM_FK FOREIGN KEY(CHAT_ROOM_NO)
		REFERENCES CHAT_ROOM(CHAT_ROOM_NO) ON DELETE CASCADE,
	CONSTRAINT CHAT_MEMBER_FK FOREIGN KEY(MEMBER_NO)
		REFERENCES MEMBER(MEMBER_NO) 
)

INSERT INTO CHAT
VALUES(CHAT_SEQ.NEXTVAL, 41, 778, 'admin', 'CHAT-CONTENT-TEST', TO_DATE('2020-9-1 3:9:1', 'YYYY-MM-DD HH24:MI:SS'));

SELECT * FROM CHAT ORDER BY CHAT_REGDATE DESC;


SELECT CHAT_ROOM_SEQ.CURRVAL FROM DUAL
INSERT INTO CHAT_USER
		VALUES(46, 784, 
			(SELECT NVL(MAX(CHAT_NO),0) FROM CHAT WHERE CHAT_ROOM_NO = 46),
			(SELECT NVL(MAX(CHAT_NO),0) FROM CHAT WHERE CHAT_ROOM_NO = 46)
		)
		
SELECT R.CHAT_ROOM_NO, R.CHAT_ROOM_NAME, C.MEMBER_ID, C.CHAT_CONTENT, C.CHAT_REGDATE,
(SELECT NVL(COUNT(CHAT_NO),0) FROM CHAT WHERE CHAT_NO > U.LAST_CHAT_NO AND CHAT_ROOM_NO = R.CHAT_ROOM_NO) AS CHAT_COUNT
FROM CHAT_ROOM R, CHAT C, CHAT_USER U
WHERE R.CHAT_ROOM_NO = C.CHAT_ROOM_NO
AND C.CHAT_ROOM_NO = U.CHAT_ROOM_NO
AND U.MEMBER_NO = 778
AND C.CHAT_NO IN (SELECT MAX(CHAT_NO) FROM CHAT GROUP BY CHAT_ROOM_NO)


----------
	
		
		
SELECT CHAT_ROOM_NO, CHAT_ROOM_NAME, 
		FROM CHAT_ROOM 
		WHERE CHAT_ROOM_NO IN 
		(SELECT CHAT_ROOM_NO FROM CHAT_USER WHERE MEMBER_NO = #{member_no})		
		
		
		
		
SELECT CHAT_ROOM_NO, CHAT_ROOM_NAME, 
		(SELECT COUNT(MEMBER_NO) FROM CHAT_USER WHERE CHAT_ROOM.CHAT_ROOM_NO = CHAT_USER.CHAT_ROOM_NO) AS COUNT_MEMBER,
		(SELECT MAX(CHAT_REGDATE) FROM CHAT WHERE CHAT_ROOM.CHAT_ROOM_NO = CHAT.CHAT_ROOM_NO) AS LAST_DATE 
		FROM CHAT_ROOM
		
		
SELECT CHAT_ROOM_NO, CHAT_ROOM_NAME, 
		(SELECT COUNT(MEMBER_NO) FROM CHAT_USER WHERE CHAT_ROOM.CHAT_ROOM_NO = CHAT_USER.CHAT_ROOM_NO) AS COUNT_MEMBER,
		(SELECT MAX(CHAT_REGDATE) FROM CHAT WHERE CHAT_ROOM.CHAT_ROOM_NO = CHAT.CHAT_ROOM_NO) AS LAST_DATE 
		FROM CHAT_ROOM
		WHERE CHAT_ROOM_NO NOT IN (SELECT CHAT_ROOM_NO FROM CHAT_USER WHERE MEMBER_NO = 778)
		ORDER BY CHAT_ROOM_NO DESC
		
		
SELECT NVL(COUNT(FIRST_CHAT_NO),0) 
		FROM CHAT_USER 
		WHERE CHAT_ROOM_NO = 7
		AND MEMBER_NO = 784 
		AND FIRST_CHAT_NO = (SELECT NVL(MAX(CHAT_NO),0) FROM CHAT WHERE CHAT_ROOM_NO = 7 )