--INTEREST_JOB

DROP TABLE INTEREST_JOB

CREATE TABLE INTEREST_JOB(
	MEMBER_NO NUMBER NOT NULL,
	JO_NO NUMBER NOT NULL,
	
	CONSTRAINT INTREST_JOB_FK_MEMBER FOREIGN KEY(MEMBER_NO)
		REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE,
	CONSTRAINT INTEREST_JOB_FK_JOBOFFER FOREIGN KEY(JO_NO)
		REFERENCES JOBOFFER(JO_NO) ON DELETE CASCADE
)

INSERT INTO INTEREST_JOB
VALUES(1, 1)

SELECT * FROM INTEREST_JOB