--JOBOFFER
DROP SEQUENCE JOBOFFERSEQ;

CREATE SEQUENCE JOBOFFERSEQ;

DROP TABLE JOBOFFER;

CREATE TABLE JOBOFFER;

-- FIELD_NO : 직무번호 , CAREER_NO : 경력번호, HIT : 조회수
CREATE TABLE JOBOFFER(
	JO_NO NUMBER NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	JO_TITLE VARCHAR2(500) NOT NULL,
	JO_CONTENT VARCHAR2(4000),
	JO_FIELD_NO	NUMBER,
	JO_CAREER_NO NUMBER,
	JO_SALARY NUMBER,
	JO_DEADLINE DATE,
	JO_HIT NUMBER,

	CONSTRAINT JO_PK_JO_NO PRIMARY KEY(JO_NO),
	CONSTRAINT JO_FK_MEMBER_NO FOREIGN KEY(MEMBER_NO)
		REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE,
	CONSTRAINT JO_FK_FIELD_NO FOREIGN KEY(JO_FIELD_NO)
		REFERENCES JO_FIELD(JO_FIELD_NO),
	CONSTRAINT JO_FK_CAREER_NO FOREIGN KEY(JO_CAREER_NO)
		REFERENCES JO_CAREER(JO_CAREER_NO)
);

SELECT * FROM JOBOFFER;

DELETE FROM JOBOFFER;

--JO_FIELD (직무)

DROP TABLE JO_FIELD;
DROP SEQUENCE JO_FIELD_SEQ;

CREATE SEQUENCE JO_FIELD_SEQ;

CREATE TABLE JO_FIELD(
	JO_FIELD_NO NUMBER NOT NULL,
	JO_FIELD_NAME VARCHAR2(50) NOT NULL,
	
	CONSTRAINT JO_FIELD_PK PRIMARY KEY(JO_FIELD_NO)
);

INSERT INTO JO_FIELD
VALUES(JO_FIELD_SEQ.NEXTVAL, '프론트엔드');

INSERT INTO JO_FIELD
VALUES(JO_FIELD_SEQ.NEXTVAL, '백엔드');

INSERT INTO JO_FIELD
VALUES(JO_FIELD_SEQ.NEXTVAL, '풀스택');

INSERT INTO JO_FIELD
VALUES(JO_FIELD_SEQ.NEXTVAL, '모바일앱');

INSERT INTO JO_FIELD
VALUES(JO_FIELD_SEQ.NEXTVAL, '빅데이터');

INSERT INTO JO_FIELD
VALUES(JO_FIELD_SEQ.NEXTVAL, '머신러닝');

INSERT INTO JO_FIELD
VALUES(JO_FIELD_SEQ.NEXTVAL, '인공지능');

INSERT INTO JO_FIELD
VALUES(JO_FIELD_SEQ.NEXTVAL, '게임');

INSERT INTO JO_FIELD
VALUES(JO_FIELD_SEQ.NEXTVAL, '네트워크');

INSERT INTO JO_FIELD
VALUES(JO_FIELD_SEQ.NEXTVAL, '보안');

INSERT INTO JO_FIELD
VALUES(JO_FIELD_SEQ.NEXTVAL, '사물인터넷');

INSERT INTO JO_FIELD
VALUES(JO_FIELD_SEQ.NEXTVAL, '블록체인');

SELECT * FROM JO_FIELD

DELETE FROM JO_FIELD


--JO_CAREER (경력)

DROP TABLE JO_CAREER;
DROP SEQUENCE JO_CAREER_SEQ;

CREATE SEQUENCE JO_CAREER_SEQ;

CREATE TABLE JO_CAREER(
	JO_CAREER_NO NUMBER NOT NULL,
	JO_CAREER_NAME VARCHAR2(50) NOT NULL,
	
	CONSTRAINT JO_CAREER_PK PRIMARY KEY(JO_CAREER_NO)
)

INSERT INTO JO_CAREER
VALUES(JO_CAREER_SEQ.NEXTVAL, '신입');

INSERT INTO JO_CAREER
VALUES(JO_CAREER_SEQ.NEXTVAL, '1년 ~ 3년');

INSERT INTO JO_CAREER
VALUES(JO_CAREER_SEQ.NEXTVAL, '3년 ~ 6년');

INSERT INTO JO_CAREER
VALUES(JO_CAREER_SEQ.NEXTVAL, '6년 ~ 10년');

INSERT INTO JO_CAREER
VALUES(JO_CAREER_SEQ.NEXTVAL, '10년 이상');

SELECT * FROM JO_CAREER

DELETE FROM JO_CAREER;