--JOBOFFER

DROP TABLE JOBOFFER
DROP SEQUENCE JOBOFFERSEQ

CREATE SEQUENCE JOBOFFERSEQ

		-- DEPTNAME : 직무 , CAREER : 경력
CREATE TABLE JOBOFFER(
	JO_NO NUMBER NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	JO_TITLE VARCHAR2(500) NOT NULL,
	JO_CONTENT VARCHAR2(4000),
	JO_DEADLINE DATE,
	JO_DEPTNAME VARCHAR2(50),
	JO_CAREER VARCHAR2(20),
	JO_SALARY NUMBER,
	
	CONSTRAINT JO_PK_JO_NO PRIMARY KEY(JO_NO),
	CONSTRAINT JO_FK_MEMBER_NO FOREIGN KEY(MEMBER_NO)
		REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE
)

INSERT INTO JOBOFFER
VALUES(JOBOFFERSEQ.NEXTVAL, 1, 'TEST-TITLE', 'TEST-CONTENT', '20/01/01', 
		'TEST-DEPTNAME', 'TEST-CAREER', 2000 )

SELECT * FROM JOBOFFER

DELETE FROM JOBOFFER