--MEMBER

DROP TABLE MEMBER
DROP SEQUENCE MEMBERSEQ

CREATE SEQUENCE MEMBERSEQ


		-- 기업회원가입 : NAME(회사명), ADDR(회사주소) -> 담당자는 CORP 테이블
		-- ROLE : ADMIN / USER / CORP
CREATE TABLE MEMBER(
	MEMBER_NO NUMBER NOT NULL,
	MEMBER_ID VARCHAR2(20) NOT NULL,
	MEMBER_PW VARCHAR2(20) ,
	MEMBER_NAME VARCHAR2(20) NOT NULL,
	MEMBER_BIRTHDAY NUMBER,
	MEMBER_POSTCODE NUMBER,
	MEMBER_ADDR VARCHAR2(500),
	MEMBER_PHONE VARCHAR2(20),
	MEMBER_EMAIL VARCHAR2(50) NOT NULL,
	MEMBER_ENABLED VARCHAR2(2) NOT NULL,
	MEMBER_ROLE VARCHAR2(10) NOT NULL,
	
	CONSTRAINT MEMBER_PK_NO PRIMARY KEY(MEMBER_NO),
	CONSTRAINT MEMBER_UQ_ID UNIQUE(MEMBER_ID),
	CONSTRAINT MEMBER_CK_ENABLED CHECK(MEMBER_ENABLED IN('Y','N'))
)

ALTER TABLE MEMBER MODIFY MEMBER_PW NULL;



INSERT INTO MEMBER
VALUES(
	MEMBERSEQ.NEXTVAL, 'admin1', '123', '관리자', '921128', '10569', '경기도 고양시', '010-0000-0000', 'admin@admin.com', 'Y', 'ADMIN'
)

INSERT INTO MEMBER
VALUES(
	MEMBERSEQ.NEXTVAL, 'user', 'useruser', '개인', '921128', '10569', '경기도 고양시', '010-0000-0000', 'user@user.com', 'Y', 'USER'
)

SELECT * FROM MEMBER ORDER BY MEMBER_NO DESC