--NEWS

DROP TABLE NEWS
DROP SEQUENCE NEWS_SEQ

CREATE SEQUENCE NEWS_SEQ

CREATE TABLE NEWS(
	NEWS_NO NUMBER NOT NULL,
	NEWS_WRITER VARCHAR2(50) NOT NULL,
	NEWS_TITLE VARCHAR2(500) NOT NULL,
	NEWS_CONTENT VARCHAR2(4000) NOT NULL,
	NEWS_REGDATE DATE NOT NULL,
	
	CONSTRAINT NEWS_PK_NO PRIMARY KEY(NEWS_NO)
)

INSERT INTO NEWS
VALUES(NEWS_SEQ.NEXTVAL, 'TEST-WRITER', 'TEST-TITLE', 'TEST-CONTENT', '20/01/01')

SELECT * FROM NEWS