--RESUME

DROP TABLE RESUME
DROP SEQUENCE RESUMESEQ

CREATE SEQUENCE RESUMESEQ

CREATE TABLE RESUME(
	RS_NO NUMBER NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	RS_IMG_NAME VARCHAR2(100),
	RS_IMG_PATH VARCHAR2(200),
	RS_SELFINTRO VARCHAR2(4000),
	
	CONSTRAINT RS_PK_NO PRIMARY KEY(RS_NO),
	CONSTRAINT RS_FK_MEMBER_NO FOREIGN KEY(MEMBER_NO)
		REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE
)

INSERT INTO RESUME
VALUES(
	RESUMESEQ.NEXTVAL, 1, 'TEST-NAME', 'TEST-PATH', 'TEST-SELFINTRO'
)

SELECT * FROM RESUME ORDER BY RS_NO DESC


--RESUME_ACADEMIC

DROP TABLE RESUME_ACADEMIC
DROP SEQUENCE RS_AC_SEQ

CREATE SEQUENCE RS_AC_SEQ
CREATE TABLE RESUME_ACADEMIC(
	RS_AC_NO NUMBER NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	RS_AC_NAME VARCHAR2(50) NOT NULL,
	RS_AC_DEPT VARCHAR2(50) NOT NULL,
	RS_AC_GRAD VARCHAR2(2) NOT NULL,
	RS_AC_START_YEAR NUMBER NOT NULL,
	RS_AC_START_MONTH NUMBER NOT NULL,
	RS_AC_END_YEAR NUMBER,
	RS_AC_END_MONTH NUMBER,
	
	CONSTRAINT RS_AC_PK_NO PRIMARY KEY(RS_AC_NO),
	CONSTRAINT RS_AC_FK_MEMBER_NO FOREIGN KEY(MEMBER_NO)
		REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE,
	CONSTRAINT RS_AC_CK_GRAD CHECK(RS_AC_GRAD IN('G','P'))
)

			-- RS_AC_GRAD : 졸업여부 (졸업 : 'G', 졸업예정 : 'P')

INSERT INTO RESUME_ACADEMIC
VALUES(
	RS_AC_SEQ.NEXTVAL, 1, 'TEST', 'TEST', 'G', 2011, 3, 2013, 2
)

SELECT * FROM RESUME_ACADEMIC ORDER BY RS_AC_NO DESC


UPDATE RESUME_ACADEMIC     
SET RS_AC_NAME = '111', RS_AC_DEPT = '11', RS_AC_GRAD = 'G',    
	RS_AC_START_YEAR = 2020, RS_AC_START_MONTH = 1,      
	RS_AC_END_YEAR = 2020, RS_AC_END_MONTH = 1    
WHERE RS_AC_NO = 302    ;     
UPDATE RESUME_ACADEMIC    
SET RS_AC_NAME = '2222', RS_AC_DEPT = '22', RS_AC_GRAD = 'G',     
	RS_AC_START_YEAR = 2020, RS_AC_START_MONTH = 1,      
	RS_AC_END_YEAR = 2020, RS_AC_END_MONTH = 1     
WHERE RS_AC_NO = 308



--RESUME_CAREER

DROP TABLE RESUME_CAREER
DROP SEQUENCE RS_CR_SEQ

CREATE SEQUENCE RS_CR_SEQ

		-- DUTY : 담당업무, DEPT : 직위
CREATE TABLE RESUME_CAREER(
	RS_CR_NO NUMBER NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	RS_CR_NAME VARCHAR2(50) NOT NULL,
	RS_CR_DUTY VARCHAR2(200) NOT NULL,
	RS_CR_DEPT VARCHAR2(50) NOT NULL,
	RS_CR_START_YEAR NUMBER NOT NULL,
	RS_CR_START_MONTH NUMBER NOT NULL,
	RS_CR_END_YEAR NUMBER,
	RS_CR_END_MONTH NUMBER,
	
	CONSTRAINT RS_CR_PK_NO PRIMARY KEY(RS_CR_NO),
	CONSTRAINT RS_CR_FK_MEMBER_NO FOREIGN KEY(MEMBER_NO)
		REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE
)


INSERT INTO RESUME_CAREER
VALUES(
	RS_CR_SEQ.NEXTVAL, 1, 'TEST-NAME', 'TEST-DUTY', 'TEST-DEPT', 2011, 3, 2013, 2
)

SELECT * FROM RESUME_CAREER


--RESUME_LICENSE

DROP TABLE RESUME_LICENSE
DROP SEQUENCE RS_LC_SEQ

CREATE SEQUENCE RS_LC_SEQ

		-- INST : 발행처/기관 ,  DATE : 취득일
CREATE TABLE RESUME_LICENSE(
	RS_LC_NO NUMBER NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	RS_LC_NAME VARCHAR2(50) NOT NULL,
	RS_LC_INST VARCHAR2(50) NOT NULL,
	RS_LC_DATE DATE NOT NULL,
	
	CONSTRAINT RS_LC_PK_NO PRIMARY KEY(RS_LC_NO),
	CONSTRAINT RS_LC_FK_MEMBER_NO FOREIGN KEY(MEMBER_NO)
		REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE
)

INSERT INTO RESUME_LICENSE
VALUES(
	RS_LC_SEQ.NEXTVAL, 1, 'TEST-NAME', 'TEST-INST', '10/01/01'
)

SELECT * FROM RESUME_LICENSE