--USERBOARD

DROP TABLE USERBOARD
DROP SEQUENCE USERBOARDSEQ

CREATE SEQUENCE USERBOARDSEQ

CREATE TABLE USERBOARD(
	USERBOARD_NO NUMBER NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	USERBOARD_TITLE VARCHAR2(500) NOT NULL,
	USERBOARD_CONTENT VARCHAR2(4000) NOT NULL,
	USERBOARD_REGDATE DATE NOT NULL,
	
	CONSTRAINT USERBOARD_PK_NO PRIMARY KEY(USERBOARD_NO),
	CONSTRAINT USERBOARD_FK_MEMBER_NO FOREIGN KEY(MEMBER_NO)
		REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE
)

INSERT INTO USERBOARD
VALUES(
	USERBOARDSEQ.NEXTVAL, 1, 'TEST', 'TEST', SYSDATE
)

SELECT * FROM USERBOARD